name: OpenTrident_DeathMessages
version: "${project.version}"
main: opentrident.deathmessages.OpenTridentDeathMessagesPlugin
api-version: "1.21"
folia-supported: true
authors:
  - "OpenTrident"
  - "Carlo"
description: A custom death messages plugin compatible with Paper and Folia.

permissions:
  opentrident.deathmessages.admin:
    description: Allows using the /deathmessages commands
    default: op
