name: OpenTrident_DeathMessages
version: 1.0.0-SNAPSHOT
main: opentrident.deathmessages.OpenTridentDeathMessagesPlugin
api-version: "1.21"
description: "A customizable, sarcastic death messages plugin for Paper and Folia."
authors: ["opentrident","CarloPlayz"]
folia-supported: true

permissions:
  opentrident.deathmessages.admin:
    description: "Allows reloading the configuration and testing messages."
    default: op
